name: Build Graal Native Image

on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build-java-8-wrapper-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: adopt
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build --stacktrace

      - name: Delete launcher-wrapper dev jar
        run: rm headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*-dev.jar
      - name: Delete launcher-wrapper javadoc jar
        run: rm headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*-javadoc.jar
      - name: Delete launcher-wrapper sources jar
        run: rm headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*-sources.jar

      - name: Rename launcher jar
        run: mv headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*.jar headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-wrapper.jar

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: launcher-wrapper-java8-jar
          path: |
            ./headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-wrapper.jar

  build:
    runs-on: ${{ matrix.os.os }}
    needs: build-java-8-wrapper-jar
    strategy:
      matrix:
        os:
          - { os: windows-latest, name: headlessmc-launcher-windows-x64 }
          - { os: ubuntu-latest, name: headlessmc-launcher-linux-x64 }
          - { os: macos-13, name: headlessmc-launcher-macos-x64 }
          #- { os: windows-11-arm, name: headlessmc-launcher-windows-arm64 } no graalvm for windows arm64 :(
          - { os: ubuntu-24.04-arm, name: headlessmc-launcher-linux-arm64 }
          - { os: macos-latest, name: headlessmc-launcher-macos-arm64 }

    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download HeadlessMc Launcher Artifact
        uses: actions/download-artifact@v4
        with:
          name: launcher-wrapper-java8-jar
      - name: Display structure of downloaded files
        run: ls -R

      - name: Output Graal Info
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew -Phmc_graal_executable=${{ matrix.os.name }} -Phmc_graal_build=true headlessmc-graalvm:nativeCompile

      - name: List files
        run: ls headlessmc-graalvm/build/native/nativeCompile

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HeadlessMc Native Image ${{ matrix.os.name }}
          path: |
            ./headlessmc-graalvm/build/native/nativeCompile/*

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: launcher-wrapper-java8-jar
