name: Release

on:
  push:
    tags:
      - '**'

jobs:
  build-graal:
    uses: 3arthqu4ke/headlessmc/.github/workflows/graal.yml@main

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: adopt
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build --stacktrace

      - name: Delete launcher dev jar
        run: rm headlessmc-launcher/build/libs/headlessmc-launcher-*-dev.jar
      - name: Delete launcher javadoc jar
        run: rm headlessmc-launcher/build/libs/headlessmc-launcher-*-javadoc.jar
      - name: Delete launcher sources jar
        run: rm headlessmc-launcher/build/libs/headlessmc-launcher-*-sources.jar

      - name: Delete launcher-wrapper dev jar
        run: rm headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*-dev.jar
      - name: Delete launcher-wrapper javadoc jar
        run: rm headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*-javadoc.jar
      - name: Delete launcher-wrapper sources jar
        run: rm headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*-sources.jar

      - name: Delete lwjgl dev jar
        run: rm headlessmc-lwjgl/build/libs/headlessmc-lwjgl-*-dev.jar
      - name: Delete lwjgl javadoc jar
        run: rm headlessmc-lwjgl/build/libs/headlessmc-lwjgl-*-javadoc.jar
      - name: Delete lwjgl sources jar
        run: rm headlessmc-lwjgl/build/libs/headlessmc-lwjgl-*-sources.jar

      - name: Delete jfx dev jar
        run: rm headlessmc-launcher-jfx/build/libs/headlessmc-launcher-jfx-*-dev.jar
      - name: Delete jfx javadoc jar
        run: rm headlessmc-launcher-jfx/build/libs/headlessmc-launcher-jfx-*-javadoc.jar
      - name: Delete jfx sources jar
        run: rm headlessmc-launcher-jfx/build/libs/headlessmc-launcher-jfx-*-sources.jar

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HeadlessMc Launcher files
          path: |
            ./headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*.jar
            ./headlessmc-launcher/build/libs/headlessmc-launcher-*.jar
            ./headlessmc-lwjgl/build/libs/headlessmc-lwjgl-*.jar
            ./headlessmc-lwjgl/build/noasm/headlessmc-lwjgl-*-no-asm.jar
            ./headlessmc-launcher-jfx/build/libs/headlessmc-launcher-jfx-*.jar
            ./headlessmc-scripts/hmc
            ./headlessmc-scripts/hmc.bat

  merge:
    runs-on: ubuntu-latest
    needs: [ build-graal, build]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true

  release:
    runs-on: ubuntu-latest
    needs: merge
    steps:
      - name: Download HeadlessMc Launcher Artifact
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            ./merged-artifacts/headlessmc-launcher-wrapper/build/libs/headlessmc-launcher-*.jar
            ./merged-artifacts/headlessmc-launcher/build/libs/headlessmc-launcher-*.jar
            ./merged-artifacts/headlessmc-lwjgl/build/libs/headlessmc-lwjgl-*.jar
            ./merged-artifacts/headlessmc-lwjgl/build/noasm/headlessmc-lwjgl-*-no-asm.jar
            ./merged-artifacts/headlessmc-launcher-jfx/build/libs/headlessmc-launcher-jfx-*.jar
            ./merged-artifacts/headlessmc-scripts/hmc
            ./merged-artifacts/headlessmc-scripts/hmc.bat
            ./merged-artifacts/headlessmc-launcher-linux-x64
            ./merged-artifacts/headlessmc-launcher-windows-x64.exe
            ./merged-artifacts/headlessmc-launcher-macos-x64
            ./merged-artifacts/headlessmc-launcher-linux-arm64
            ./merged-artifacts/headlessmc-launcher-macos-arm64
